language: go

go:
  - 1.6
  - tip

services:
  - mysql
  
before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('123456') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - mysql -e "create database IF NOT EXISTS test;" -uroot -p123456
  - mysql -uroot -p123456 test < testfiles/test.sql

script:
  - go test -v .
  - go test -v ./model/Mysql
  - go test -v ./validator
  