Mode: TEST
Listenaddr: localhost
Listenport: 8080
PubDir: testfiles
Db:
    SqlDriver: MySQL
    Protocol: tcp
    Hostname: localhost
    Username: root
    Password: 123456
    Dbname: test
    Charset: utf8